### ISSUE TITLE
new Pi Image

### ISSUE THREAD

**Issue by craigreilly** [dsmithson/SpyderTallyController#15]
Is anyone able to create a new Pi image with the recent changes?
I do not understand how to take the changes that fix the issue (fails if there is no display screen)

**Comment by dsmithson** [comment]
Hi @craigreilly!  The instructions for creating a new SD card image are in this [README](https://github.com/dsmithson/SpyderTallyController/blob/master/docs/Linux/README.md)within the repository, however I did create a new release with an updates SD card image with the last changes that made the front panel display optional.  This is in release 1.0.1, which you can download from [here](https://github.com/dsmithson/SpyderTallyController/releases).

Sorry, I probably should have called that out on the related issue that this was fixed as a part of.  Give it a try and let me know how it goes!

**Comment by craigreilly** [comment]
Not super familiar with Github. I was only seeing 1.0.0. I see this new version now and finally have a config screen -  thank you!
